# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Black format check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Format check
      run: |
        black src --check --line-length=120 --target-version=py311
      continue-on-error: false
